### ISSUE TITLE
 java.lang.InterruptedException

### ISSUE THREAD

**Issue by rolfen** [MajeurAndroid/Adb-Remote-Screen#16] opened 2018-06-11 19:10 UTC
I can't connect to my phone running Android 4 (Debug mode enabled).
I can see an ID when I plug it in, but when I click on it, nothing happens, and I see this in the console:
```

java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:328)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1361)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at com.majeur.ars.ScreenPanel$UpdateThread.repaintPanel(ScreenPanel.java:238)
	at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:222)

```

I have tried the Vysor app for Chrome, which I use to connect on Windows. It complains that it could not install the APK on my phone.

**Comment by MajeurAndroid** [comment] 2020-05-08 13:45
Duplicate of #9

**Closed as completed by MajeurAndroid** 2020-05-08 13:45 UTC
