### ISSUE TITLE
i am stuck here unable to install cannbera gtk module

### ISSUE THREAD

**Issue by Pranjalkurrey** [MajeurAndroid/Adb-Remote-Screen#17] opened 2018-08-02 11:44 UTC
![whatsapp image 2018-08-02 at 4 38 19 pm](https://user-images.githubusercontent.com/26349120/43581691-7ada907c-9677-11e8-8f56-0f7e942c0546.jpeg)

**Comment by MajeurAndroid** [comment] 2018-09-05 22:12
Duplicate of #14

**Closed as completed by MajeurAndroid** 2018-09-05 22:12 UTC
